### ISSUE TITLE
TypeError: null is not an object (evaluating 'IntercomEventEmitter.UNREAD_COUNT_CHANGE_NOTIFICATION')

### ISSUE THREAD

**Issue by SergeWilfried** [cmaycumber/config-plugin-react-native-intercom#15]
I'm getting the intercomEventEmitter issue. I'm using Expo to build the React Native application.

```
...
    "@intercom/intercom-react-native": "2.0.3",
    "config-plugin-react-native-intercom": "^1.2.0",
    "expo": "^44.0.0",
...
```

Error

```
TypeError: null is not an object (evaluating 'IntercomEventEmitter.UNREAD_COUNT_CHANGE_NOTIFICATION')
- ... 9 more stack frames from framework internals

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

**Comment by maxipetrucci** [comment]
Same here! Also tried with old versions of package and plugin

**Comment by Chris-Beckett** [comment]
This issue is already open in the current issue: https://github.com/cmaycumber/config-plugin-react-native-intercom/issues/6

**Comment by cmaycumber** [comment]
@SergeWilfried Can you try using `Intercom.displayMessenger();` and let me know if that also has the problem?

**Comment by cmaycumber** [comment]
Also make sure when you install the package to run a fresh `expo prebuild --clean`.
