### ISSUE TITLE
eas development client crash on Android

### ISSUE THREAD

**Issue by nicolas-meilan** [cmaycumber/config-plugin-react-native-intercom#44]
The developement client eas build crash on Android before show the expo UI.
When I make a build with non `developmentClient: true`, the app does not crash.

- expo version: 5.4.3
- expo sdk: 45
- @intercom/intercom-react-native": "^3.0.5"
- "config-plugin-react-native-intercom": "^1.6.10"

eas config:
```
    "development": {
      "extends": "base",
      "releaseChannel": "X",
      "developmentClient": true,
      "env": {
        ...
      },
      "android": {
        "distribution": "internal"
      },
      "ios": {
        "simulator": true
      }
```

plugin config: 

```
"plugins": [
    [
      "config-plugin-react-native-intercom",
      {
        "iosApiKey": "X",
        "androidApiKey": "X",
        "appId": "X"
      }
    ]
  ]
```

Device crash log:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/dsl/ModuleKt;
	at expo.modules.devlauncher.koin.DevLauncherKoinAppKt.<clinit>(DevLauncherKoinApp.kt:16)
	at expo.modules.devlauncher.koin.DevLauncherKoinAppKt.access$getKoinAppFactory$p(DevLauncherKoinApp.kt:1)
	at expo.modules.devlauncher.koin.DevLauncherKoinContext.<clinit>(DevLauncherKoinApp.kt:35)
	at expo.modules.devlauncher.DevLauncherController$Companion.wasInitialized(DevLauncherController.kt:345)
	at expo.modules.devlauncher.rncompatibility.DevLauncherReactNativeHostHandler.getUseDeveloperSupport(DevLauncherReactNativeHostHandler.kt:21)
	at expo.modules.ReactNativeHostWrapperBase$getUseDeveloperSupport$1.invoke(ReactNativeHostWrapperBase.kt:80)
	at expo.modules.ReactNativeHostWrapperBase$getUseDeveloperSupport$1.invoke(ReactNativeHostWrapperBase.kt:80)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
	at expo.modules.ReactNativeHostWrapperBase.getUseDeveloperSupport(ReactNativeHostWrapperBase.kt:81)
	at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager(ReactNativeHostWrapperBase.kt:26)
	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
	at com.group.project.devclient.MainApplication.onCreate(MainApplication.java:69)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1212)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7103)
	at android.app.ActivityThread.access$1600(ActivityThread.java:271)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8309)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.dsl.ModuleKt" on path: DexPathList[[zip file "/data/app/~~4HBDN_LQHNIZxK8sELDZ2Q==/com.group.project.devclient-plvKrvB5afHtY4faDMT4FA==/base.apk"],nativeLibraryDirectories=[/data/app/~~4HBDN_LQHNIZxK8sELDZ2Q==/com.group.project.devclient-plvKrvB5afHtY4faDMT4FA==/lib/arm64, /data/app/~~4HBDN_LQHNIZxK8sELDZ2Q==/com.group.project.devclient-plvKrvB5afHtY4faDMT4FA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 26 more
```

**Comment by nicolas-meilan** [comment]
Sorry, this error is about another lib
